-- AlterTable
ALTER TABLE "Commute" ALTER COLUMN "inwardTime" DROP DEFAULT,
ALTER COLUMN "inwardTime" SET DATA TYPE TEXT,
ALTER COLUMN "outwardTime" DROP DEFAULT,
ALTER COLUMN "outwardTime" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "CommuteTemplate" ALTER COLUMN "inwardTime" DROP DEFAULT,
ALTER COLUMN "inwardTime" SET DATA TYPE TEXT,
ALTER COLUMN "outwardTime" DROP DEFAULT,
ALTER COLUMN "outwardTime" SET DATA TYPE TEXT;
