import { TopBar } from "@/components/TopBar";
import { api } from "@/utils/api";
import type { NextPage } from "next";
import Head from "next/head";

const Stops: NextPage = () => {
  const stops = api.stop.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="bg-red-400">
          <ul>
            {stops.data?.map((stop) => (
              <li key={stop.id}>{stop.name}</li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Stops;
